stages:
  - build
  - deploy

build:
  image: node:20
  stage: build
  script:
#    - cd packages/public/client/
    - npm install
    - npm run build
  tags:
    - deploy
  only:
    refs:
      - main

deploy-frontend:
  stage: deploy
  script:
    - sudo cp -r -f dist/* /var/www/epi-vis.designinformatics.org/html
  tags:
    - deploy
  only:
    refs:
      - main