stages:
  - build
  - deploy

build:
  stage: build
  script:
#    - export PATH="$PATH:/home/ubuntu/.nvm/versions/node/v21.7.0/bin"
    - /home/ubuntu/.nvm/versions/node/v21.7.0/lib/node_modules/npm run build
  tags:
    - deploy
  only:
    refs:
      - main

deploy-frontend:
  stage: deploy
  script:
    - sudo cp -r -f dist/* /var/www/epi-vis.designinformatics.org/html
  tags:
    - deploy
  only:
    refs:
      - main